### ISSUE TITLE
Could not load image

### ISSUE THREAD

**Issue by tonine1337** [vogievetsky/KoalasToTheMax#6]
Sir,
I am a newbie in these kinds of things. But it seems to cannot locate the images as soon as I load the page an alert pops up which says "Could not load image img/_imageName_". I tried the default ones and the custom ones but the problem still persists. Could you please help me.

![capture](https://cloud.githubusercontent.com/assets/14199391/14943382/ffc4fca2-0ff4-11e6-88f6-5c1b52a40635.JPG)

Thank You

**Comment by abhishek-2102** [comment]
Even I got the same by running the index.html file without loading it in the server. Run the project with all the required files in a server and then try it, this fixed my issue.

P.S. This answer might be very late.
